config/routes.rb
Rails.application.routes.draw do
  root to: 'workflows#index'
  resources :workflows
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/work_flow.rb
class WorkFlow < ApplicationRecord


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/workflows_controller.rb
class WorkflowsController < ApplicationController
def index
    @workflows = WorkFlow.all
end

def new
    @workflow = params
end

def create
    @workflow = WorkFlow.new
    @workflow.save
end

def delete
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workflows_helper.rb
module WorkflowsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | WorkShare
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/users/edit.html.slim
h1 Users#edit
p Find me in app/views/users/edit.html.slim

app/views/users/index.html.slim
h1 Users#index


p

= link_to  '投稿', new_workflow_path, class: 'btn btn-primary'

app/views/users/new.html.slim
h1 Users#new
p Find me in app/views/users/new.html.slim

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim

app/views/workflows/create.html.slim
h1 Workflows#create
p Find me in app/views/workflows/create.html.slim

app/views/workflows/delete.html.slim
h1 Workflows#delete
p Find me in app/views/workflows/delete.html.slim

app/views/workflows/index.html.slim
h1 Workflows#index
p Find me in app/views/workflows/index.html.slim
= link_to '投稿', new_workflow_path, class: 'btn btn-primary'

app/views/workflows/new.html.slim
h1 new
.nav.justify-content-end
 = link_to '一覧', workflows_path, class: 'nav-link'

=form_with model: @workflow, local: true do |f|
    .form-group
     = f.label :title
     = f.text_field :title, class: 'form-control'
    .form-group
     = f.label :content
     = f.text_field :content, class: 'form-control'
    = f.submit nil, class: 'btn btn-primary'